runtime: nodejs10

instance_class: F2

env_variables:
    MONGODB_URL: "mongodb+srv://admin-ray:aim841104@cluster0-j7ls4.mongodb.net/ReactKeeper?retryWrites=true&w=majority"
    JWT_SECRET: thisisasecretformyapp
    
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto